version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.9.0-browsers
    steps:
    - checkout
    # Log the current branch
    - run: 
        name: Show current branch
        command: echo ${CIRCLE_BRANCH} 
    - run:
        name: Show current directory
        command: pwd
    - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-
    - run: 
        name: Install dependencies
        command: yarn
    - save_cache: 
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run:
        name: Building
        command: yarn build:prod
    - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1}}
        paths:
        - public
        - package.json
        - firebase.json
        - .firebaserc
workflows:
  version: 2
  -deploy:
    jobs:
    - build
