version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.9.0-browsers
    steps:
    - checkout
    - run: 
        name: Show current branch
        command: echo ${CIRCLE_BRANCH} 
    - run:
        name: Show current directory
        command: pwd
    - restore_cache:
         keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
    - run: 
        name: Install dependencies
        command: yarn
    - save_cache: 
        key: v1-dependencies-{{ checksum "yarn.lock" }}
        paths:
        - node_modules
    - run:
        name: Run Unit Tests
        command: yarn test
workflows:
  version: 2
  test_and_deploy:
    jobs:
        - test
