version: 2
jobs: 
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9.3-browsers
    steps:
      - checkout
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
      - run:
        name: Show current directory
        command: pwd
      - restore_cache:
        keys: - v1-dependencies-{{checksum "package.json"}}
      - run:
        name: Install dependencies
        command: yarn
      - save_cache:
        key: v1-dependencies-{{ checksum "package.json"}}
        paths: 
          - node_modules
      - run: 
        name: Building
        command: yarn build:prod
      - save_cache:
        key: v1-dist-{{.ENVIRONMENT.CIRCLE_BRANCH}}-{{.ENVIRONMENT.CIRCLE_SHA1}}
        paths:
          - dist
          - package.json
          - firebase.json
          - .firebaserc
  deploy:
    docker: 
      - image: circleci/node:chakracore-8.11-browsers-legacy
    working_directory: ~/project
    steps:
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
      - restore_cache:
        key: v1-dist-{{.ENVIRONMENT.CIRCLE_BRANCH}}-{{.ENVIRONMENT.CIRCLE_SHA1}}
      - run:
        name: Install Firebase
        command: yarn add -D firebase-tools
      - run: 
        name: Deploy master to firebase
        command: yarn deploy:ci
workflows:
  version: 2
  - deploy:
    jobs:
      - build
      - deploy: 
        requires: 
          - build
        filters:
          branches:
            only: master

