version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
    - image: circleci/node:latest-browsers
    steps:
    - checkout
    - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
    - run:
        name: Show current directory
        command: pwd
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
    - run:
        name: Install dependencies
        command: npm install
    - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
        - node_modules
    - run: 
        name: E2E Tests
        command: npm run test
    - run:
        name: Building
        command: npm run build:prod
    - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - public
        - package.json
        - firebase.json
        - .firebaserc
  deploy:
    docker:
    - image: circleci/node:latest-browsers
    working_directory: ~/project
    steps:
    - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
    - restore_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
    - run:
        name: Install Firebase
        command: npm install --save-dev firebase-tools
    - run:
        name: Deploy Master to Firebase
        command: ./node_modules/.bin/firebase deploy --token=1/U9IboSnnODTBfV6wcdbVmBeZyacL88OD9UeFqs71gb0
workflows:
  version: 2
  -deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master